django/learn/courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.course_list),
    url(r'(?P<pk>\d+)/$', views.course_detail),
]

django/learn/learning_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^courses/', include('courses.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.hello_world),
]

urlpatterns += staticfiles_urlpatterns()

django/learn/courses/models.py
from django.db import models


class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    
    def __str__(self):
        return self.title


class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course)
    
    class Meta:
        ordering = ['order',]
    
    def __str__(self):
        return self.title

django/learn/courses/views.py
from django.shortcuts import get_object_or_404, render

from .models import Course


def course_list(request):
    courses = Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses': courses})


def course_detail(request, pk):
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})

django/learn/learning_site/views.py
from django.shortcuts import render


def hello_world(request):
    return render(request, 'home.html')

django/learn/courses/templates/courses/course_detail.html
{% extends "layout.html" %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}
<article>
    <h2>{{ course.title }}</h2>
    {{ course.description }}
    
    <section>
        {% for step in course.step_set.all %}
            <h3>{{ step.title }}</h3>
            {{ step.description }}
        {% endfor %}
    </section>
</article>
{% endblock %}

django/learn/courses/templates/courses/course_list.html
{% for course in courses %}
<h2>{{ course.title }}</h2>
{{ course.description }}
{% endfor %}

django/learn/templates/home.html
{% extends "layout.html" %}

{% block title %}Well hello there!{% endblock %}

{% block content %}
<h1>Welcome!</h1>
{% endblock %}

django/learn/templates/layout.html
{% load static from staticfiles %}

<!doctype html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    </head>
    <body>
        <div class="site-container">
        {% block content %}{% endblock %}
        </div>
    </body>
</html>